[project]
name = "edms-assistant"
version = "0.1.0"
description = "AI-агент для интеграции с электронной системой управления документами (EDMS)"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
readme = "README.md"
requires-python = ">=3.14,<4.0.0"
dependencies = [
    "langgraph>=1.0.0,<2.0.0",
    "langchain>=1.0.0",
    "langchain-community>=1.0.0a1",
    "langgraph[checkpoint]>=1.0.0",
#    "asyncpg>=0.30.0",
    "langchain-openai>=1.0.1",
    "uv>=0.9.5",
    "httpx>=0.27.0",
    "fastapi>=0.120.0",
    "uvicorn>=0.38.0",
    "transformers>=4.57.1",
    "aiohttp>=3.13.1",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "python-multipart>=0.0.20",
    "typer>=0.19.2",
    "PyYAML>=6.0.3",
    "opentelemetry-api>=1.38.0",
    "opentelemetry-sdk>=1.38.0",
    "opentelemetry-instrumentation>=0.59b0",
    "psycopg[binary]>=3.2.12",
    "langsmith>=0.4.38",
    "python-docx>=1.2.0",
    "PyPDF2>=3.0.1",
    "docx2txt>=0.9",
    "python-dotenv>=1.2.1",
    "opentelemetry-api>=1.38.0",
    "opentelemetry-sdk>=1.38.0",
    "opentelemetry-instrumentation-fastapi>=0.59b0",
    "opentelemetry-instrumentation-httpx>=0.59b0",
    "opentelemetry-exporter-otlp>=1.38.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.14.2",
    "black>=25.9.0",
    "isort>=5.13.2",
    "mypy>=1.18.2",
    "pytest-asyncio>=1.2.0",
    "datamodel-code-generator>=0.35.0",
]

# Настройки сборки
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/edms_assistant"]
sources = ["src"]

# -------- Настройки инструментов --------
[tool.ruff]
line-length = 88
target-version = "py313"

[tool.black]
line-length = 88
target-version = ["py313"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.13"
namespace_packages = true
explicit_package_bases = true
disable_error_code = ["import-untyped"]
exclude = ["^build/"]
